right_arm:
  planner_configs:
    right_arm_ARA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_ARA_BFS_WS:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmWorkspaceConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_MHA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_LARA_BFS_ML:
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_EGWA_DEG_MLEG:
      search_config: EGWAConfigDefault
      heuristic_config: BFSEGraphConfig
      graph_config: RightArmManipLatticeEgraphConfigDefault
      shortcut_config: PVJointConfigDefault

right_arm_and_torso:
  planner_configs:
    right_arm_and_torso_ARA_BFS_ML:
      search_config: ARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_ARA_JD_ML:
      search_config: ARAConfigDefault
      heuristic_config: JointDistConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_MHA_BFS_ML:
      search_config: MHAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault
    right_arm_and_torso_LARA_BFS_ML:
      search_config: LARAConfigDefault
      heuristic_config: BFSConfigDefault
      graph_config: RightArmAndTorsoManipLatticeConfigDefault
      shortcut_config: PVJointConfigDefault

search_configs:
  ARAConfigDefault:
    search: arastar
    epsilon: 100.0
  MHAConfigDefault:
    search: mhastar
    epsilon: 100.0
    mha_epsilon: 100.0
  LARAConfigDefault:
    search: larastar
    epsilon: 100.0
  EGWAConfigDefault:
    search: egwastar
    epsilon: 100.0

heuristic_configs:
  BFSConfigDefault:
    heuristic: bfs
    bfs_res_x: 0.015
    bfs_res_y: 0.015
    bfs_res_z: 0.015
    bfs_sphere_radius: 0.02
  BFSEGraphConfig:
    heuristic: bfs_egraph
    egraph_epsilon: 20.0
    bfs_res_x: 0.04
    bfs_res_y: 0.04
    bfs_res_z: 0.04
    bfs_sphere_radius: 0.02
  JointDistConfigDefault:
    heuristic: joint_distance

graph_configs:
  RightArmManipLatticeConfigDefault:
    graph: manip
    discretization:
      r_shoulder_pan_joint: 0.010
      r_shoulder_lift_joint: 0.010
      r_upper_arm_roll_joint: 0.010
      r_elbow_flex_joint: 0.010
      r_forearm_roll_joint: 0.010
      r_wrist_flex_joint: 0.010
      r_wrist_roll_joint: 0.010
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmManipLatticeEgraphConfigDefault:
    graph: manip_lattice_egraph
    discretization:
      r_shoulder_pan_joint: 0.010
      r_shoulder_lift_joint: 0.010
      r_upper_arm_roll_joint: 0.010
      r_elbow_flex_joint: 0.010
      r_forearm_roll_joint: 0.010
      r_wrist_flex_joint: 0.010
      r_wrist_roll_joint: 0.010
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4
  RightArmWorkspaceConfigDefault:
    graph: workspace
  RightArmAndTorsoManipLatticeConfigDefault:
    graph: manip
    # angular resolution of each active joint variable
    discretization:
      r_shoulder_pan_joint: 0.010
      r_shoulder_lift_joint: 0.010
      r_upper_arm_roll_joint: 0.010
      r_elbow_flex_joint: 0.010
      r_forearm_roll_joint: 0.010
      r_wrist_flex_joint: 0.010
      r_wrist_roll_joint: 0.010
      torso_lft_joint: 0.010
    # mprim_filename: uploaded via roslaunch
    use_xyz_snap_mprim: false
    use_rpy_snap_mprim: false
    use_xyzrpy_snap_mprim: true
    use_short_dist_mprims: true
    xyz_snap_dist_thresh: 0.0
    rpy_snap_dist_thresh: 0.04
    xyzrpy_snap_dist_thresh: 0.04 #0.2
    short_dist_mprims_thresh: 0.4

shortcut_configs:
  PVJointConfigDefault:
    shortcut_path: true
    shortcutter: joint_position_velocity_space
    interpolate_path: true
