#Independent settings for the global costmap
global_costmap: 
  publish_voxel_map: true
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: false
